---
kind: pipeline
type: docker
name: deploy

- name: move files to production
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: host_prod
    username:
      ci_user
    key:
      from_secret: ssh_key_prod
    port: 22
    target: /home/ci_user/deploy
  when:
    branch:
      - main

- name: deploy to production
  image: appleboy/drone-ssh
  settings:
    script:
      - rm -rf /home/ci_user/deploy/.git
      - rm -rf /home/ci_user/deploy/phpcs.phar
      - /bin/cp -rf /home/ci_user/deploy/* /var/www/html/kissakalenteri
    host:
      from_secret: host_prod
    username:
      ci_user
    key:
      from_secret: ssh_key_prod
  when:
    branch:
      - main